# Generated by Django 5.2 on 2025-07-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_lecture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
