# Generated by Django 5.2 on 2025-05-06 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryQuizCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcompletion')),
                ('id_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.history')),
            ],
        ),
    ]
