# Generated by Django 5.2 on 2025-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
